# Generated by Django 4.2.7 on 2025-11-24 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('threads', 'Threads'), ('other', 'Outro')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('entered_by', models.CharField(max_length=100)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Manual entries',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('avg_session_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('organic_traffic', models.IntegerField(blank=True, default=0, null=True)),
                ('direct_traffic', models.IntegerField(blank=True, default=0, null=True)),
                ('referral_traffic', models.IntegerField(blank=True, default=0, null=True)),
                ('social_traffic', models.IntegerField(blank=True, default=0, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['collected_at'], name='api_website_collect_0297c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('threads', 'Threads')], max_length=20)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(blank=True, default=0, null=True)),
                ('posts_count', models.IntegerField(blank=True, default=0, null=True)),
                ('engagement_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.IntegerField(blank=True, default=0, null=True)),
                ('shares', models.IntegerField(blank=True, default=0, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['platform', 'collected_at'], name='api_socialm_platfor_a192c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Google Play'), ('ios', 'App Store')], max_length=10)),
                ('total_downloads', models.IntegerField(default=0)),
                ('daily_downloads', models.IntegerField(blank=True, default=0, null=True)),
                ('weekly_downloads', models.IntegerField(blank=True, default=0, null=True)),
                ('monthly_downloads', models.IntegerField(blank=True, default=0, null=True)),
                ('active_users', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['platform', 'collected_at'], name='api_appdown_platfor_0c57c0_idx')],
            },
        ),
    ]
